---
title: "hw_5_R"
author: "Stephanie Pusker"
date: "2022-11-13"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, error = FALSE)
```

```{r, data cleaning}

library(tidyverse)
library(stringr)
library(purrr)
library(broom)
library(scales)
library(ggthemes)
library(sf)
library(tigris)
library(lubridate)
library(flexdashboard)
library(shiny)
library(jsonlite)
library(maptools)
library(leaflet)
library(plotly)
library(DT)
library(viridis)
library(rgdal)

homicides <- read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")

homicides <- homicides %>% 
  unite(city_name, city, state, sep = ", ")

homicides %>% 
  group_by(city_name) %>% 
  summarize(total = n()) %>% 
  arrange(desc(total)) %>% 
  slice(-51) 

dc_homicides <- homicides %>% 
  filter(city_name == "Washington, DC") %>% 
  mutate(reported_date = ymd(reported_date))

dc_homicides

```


```{r, more data cleaning}

dc_districts <- state_legislative_districts(state = "DC", cb = TRUE, class = "sf")

unique(dc_homicides$victim_race)

dc_homicides %>% 
  group_by(victim_race) %>% 
  summarise(total = n())

dc_race <- dc_homicides %>%
  mutate(unsolved = disposition != "Closed by arrest") %>% 
  group_by(victim_race) %>% 
  arrange(desc(victim_race)) %>% 
  mutate(victim_race = fct_lump(victim_race)) %>% 
  filter(!victim_race == c("Other", "Asian")) %>% 
  ungroup() %>% 
  slice(-c(43:45),
        -c(1328:1334))

dc_race$unsolved <- as.numeric(dc_race$unsolved)

dc_race %>% 
  group_by(victim_race) %>% 
  summarise(total = n())

```


```{r}

EPSG <- make_EPSG()

dc_race_crs <- st_as_sf(dc_race, coords = c("lon", "lat")) %>% 
  st_set_crs(2248)

dc_districts_crs <- st_as_sf(dc_districts, coords = c("lon", "lat")) %>% 
  st_set_crs(2248)

unsolved_names <- c(`0` = "Solved", `1` = "Unsolved")

cols <- c("")

ggplot() +
  geom_sf(data = dc_districts_crs, fill = "gray87", color = "gray57", 
          alpha = 0.5) +
  geom_sf(data = dc_race_crs, aes(color = victim_race),
          size = 2, alpha = 0.5) +
  facet_wrap(~ unsolved, labeller = labeller(.cols = unsolved_names)) +
  ggtitle("Locations of Homicides in DC by Race and Solved Status") +
  guides(color = guide_legend(title = "Victim Race")) +
  scale_color_manual(values = c("Black" = "dodgerblue4", "Hispanic" = "deeppink2",
                                "White" = "darkorchid1")) +
  theme_map()
  
```

